version: '0.1'
services:
  frontend:
    image: vue-app
    build: .
    ports:
      - 127.0.0.1:8080:8080
  backend:
    image: fastify-api
    build: .
    ports:
      - 127.0.0.1:4000:4000
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_PASSWORD: "password"
    ports:
      - 127.0.0.1:3306:3306
