version: '3.8'
services:
  db:
    image: mysql
    container_name: fastify-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 0
    ports:
      - 3306:3306

  backend:
    build: ./api
    container_name: fastify-api
    depends_on:
      "db":
        condition: service_healthy
      "frontend":
        condition: service_healthy
    ports:
      - 5001:5001

  frontend:
    build: ./vue-app
    container_name: vue-app
    depends_on:
      "db":
        condition: service_healthy
    ports:
      - 8080:8080
